name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.f"
      - "**.cpp"
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_linux.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends g++ gfortran liblapack-dev libboost-filesystem-dev libboost-regex-dev

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran
        CC: gcc
