name: ci_mac
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_mac.yml"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install lapack boost ninja

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9
