name: ci_mac

on:
  push:
    paths:
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_cmake.yml"
  pull_request:


jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install lapack boost

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9
